### ISSUE TITLE
Do secrets work in flake?

### ISSUE THREAD

**Issue by hgl** [Xe/nixos-configs#5]
First of all, thanks for sharing your configs and your blog post on how to manage secrets. They are very helpful.

However I couldn't make the secrets work with my NixOS config which is defined in flake. When I specified a secret file as the source, nix complained that the secret didn't exist. The reason seems to be that since it's ignored by git, it's ignored by flake too?

I wonder does that mean git ignored secrets won't work in flake?

**Comment by Xe** [comment]
They won't work in flakes, no. Use [agenix](https://github.com/ryantm/agenix) instead.

**Comment by hgl** [comment]
Cool, thanks for the heads up.
